apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: tramplin
    user: tramplin
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 5
    secureJsonData:
      password: tramplin
    isDefault: true
    editable: true
